{
gSystem->Load("libdiphotonsUtils");
double harray[20]={0.0,0.1,0.2,0.5,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0,6.0,7.0,8.0,9.0,10.0,12.0,15.0};
//TFile* f1=TFile::Open("templatesanv1_v19_256_config256.root");
//TFile *f1=TFile::Open("checkofTemplatescreation087/mix_246_v19.root");
//TFile *f2 = TFile::Open("mix_v19_087.root");
TFile *f1 = TFile::Open("templatesanv1_v19_137_config256short2NoPreselectionotherhalf.root");
TFile *f2 = TFile::Open("templatesanv1_v19_137_config256short2NoPreselectionhalf.root");
TCanvas *c1=new TCanvas("c1","c1")       ;      
c1.cd();
c1.SetLogy();
f1::tree_template_p_singlePho_eta_inclusive->SetLineColor(kRed);
f1::tree_template_p_singlePho_eta_inclusive->Draw("phoPhoIso","weight");
f2::tree_template_p_singlePho_eta_inclusive->SetLineStyle(10);
f2::tree_template_p_singlePho_eta_inclusive->SetLineColor(kBlue);
f2::tree_template_p_singlePho_eta_inclusive->Draw("phoPhoIso","weight","same");
TCanvas *c2=new TCanvas("c2","c2")       ;      
c2.cd();
c2.SetLogy();
f1::tree_template_p_singlePho_eta_inclusive->SetLineStyle(1);
f1::tree_template_p_singlePho_eta_inclusive->SetLineColor(kRed);
f1::tree_template_p_singlePho_eta_inclusive->Draw("templateNdim1Dim0","weight");
f2::tree_template_p_singlePho_eta_inclusive->SetLineStyle(10);
f2::tree_template_p_singlePho_eta_inclusive->SetLineColor(kBlue);
f2::tree_template_p_singlePho_eta_inclusive->Draw("templateNdim1Dim0","weight","same");

TCanvas *c2a=new TCanvas("c2a","c2a")       ;      
c2a.cd();
c2a.SetLogx();
c2a.SetLogy();
f1::tree_template_p_singlePho_eta_inclusive->SetLineStyle(1);
f1::tree_template_p_singlePho_eta_inclusive->SetLineColor(kRed);
f1::tree_template_p_singlePho_eta_inclusive->Draw("phoPt>>h21(100,1.,13000.)","weight");
f2::tree_template_p_singlePho_eta_inclusive->SetLineStyle(10);
f2::tree_template_p_singlePho_eta_inclusive->SetLineColor(kBlue);
f2::tree_template_p_singlePho_eta_inclusive->Draw("phoPt>>h22(100,1.,13000.)","weight","same");




TCanvas *c3=new TCanvas("c3","c3")       ;      
c3.Divide(2,1);
c3.cd(1);
gPad->SetLogy();
f1::tree_data_2D_EBEB->SetLineColor(kRed);
f1::tree_data_2D_EBEB->SetLineStyle(1);
f1::tree_data_2D_EBEB->Draw("templateNdim2Dim0","weight");
f2::tree_data_2D_EBEB->SetLineStyle(10);
f2::tree_data_2D_EBEB->SetLineColor(kBlue);
f2::tree_data_2D_EBEB->Draw("templateNdim2Dim0","weight","same");
c3.cd(2);
gPad->SetLogy();
f1::tree_data_2D_EBEB->SetLineStyle(1);
f1::tree_data_2D_EBEB->SetLineColor(kRed);
f1::tree_data_2D_EBEB->Draw("templateNdim2Dim1","weight");
f2::tree_data_2D_EBEB->SetLineStyle(10);
f2::tree_data_2D_EBEB->SetLineColor(kBlue);
f2::tree_data_2D_EBEB->Draw("templateNdim2Dim1","weight","same");

TCanvas *c4=new TCanvas("c4","c4")       ;      
c4.Divide(2,1);
c4.cd(1);
gPad->SetLogy();
f1::tree_data_2D_EBEB->SetLineColor(kRed);
f1::tree_data_2D_EBEB->SetLineStyle(1);
f1::tree_data_2D_EBEB->Draw("leadPhoIso","weight");
f2::tree_data_2D_EBEB->SetLineStyle(10);
f2::tree_data_2D_EBEB->SetLineColor(kBlue);
f2::tree_data_2D_EBEB->Draw("leadPhoIso","weight","same");
c4.cd(2);
gPad->SetLogy();
f1::tree_data_2D_EBEB->SetLineColor(kRed);
f1::tree_data_2D_EBEB->SetLineStyle(1);
f1::tree_data_2D_EBEB->Draw("subleadPhoIso","weight");
f2::tree_data_2D_EBEB->SetLineStyle(10);
f2::tree_data_2D_EBEB->SetLineColor(kBlue);
f2::tree_data_2D_EBEB->Draw("subleadPhoIso","weight","same");

TCanvas *c5=new TCanvas("c5","c5")       ;    
c5.Divide(2,1);
c5.cd(1);
gPad->SetLogy();
f1::tree_data_2D_EBEE->SetLineColor(kRed);
f1::tree_data_2D_EBEE->SetLineStyle(1);
f1::tree_data_2D_EBEE->Draw("templateNdim2Dim0","weight");
f2::tree_data_2D_EBEE->SetLineColor(kBlue);
f2::tree_data_2D_EBEE->SetLineStyle(10);
f2::tree_data_2D_EBEE->Draw("templateNdim2Dim0","weight","same");
c5.cd(2);
gPad->SetLogy();
f1::tree_data_2D_EBEE->SetLineColor(kRed);
f1::tree_data_2D_EBEE->SetLineStyle(1);
f1::tree_data_2D_EBEE->Draw("templateNdim2Dim1","weight");
f2::tree_data_2D_EBEE->SetLineStyle(10);
f2::tree_data_2D_EBEE->SetLineColor(kBlue);
f2::tree_data_2D_EBEE->Draw("templateNdim2Dim1","weight","same");

TCanvas *c6=new TCanvas("c6","c6")       ;      
c6.Divide(2,1);
c6.cd(1);
gPad->SetLogy();
f1::tree_data_2D_EBEE->SetLineColor(kRed);
f1::tree_data_2D_EBEE->SetLineStyle(1);
f1::tree_data_2D_EBEE->Draw("leadPhoIso","weight");
f2::tree_data_2D_EBEE->SetLineStyle(10);
f2::tree_data_2D_EBEE->SetLineColor(kBlue);
f2::tree_data_2D_EBEE->Draw("leadPhoIso","weight","same");
c6.cd(2);
gPad->SetLogy();
f1::tree_data_2D_EBEE->SetLineColor(kRed);
f1::tree_data_2D_EBEE->SetLineStyle(1);
f1::tree_data_2D_EBEE->Draw("subleadPhoIso","weight");
f2::tree_data_2D_EBEE->SetLineStyle(10);
f2::tree_data_2D_EBEE->SetLineColor(kBlue);
f2::tree_data_2D_EBEE->Draw("subleadPhoIso","weight","same");


TCanvas *c7=new TCanvas("c7","c7")       ;      
c7.Divide(2,1);
c7.cd(1);
gPad->SetLogy();
gPad->SetLogx();
f1::tree_data_2D_EBEE->SetLineColor(kRed);
f1::tree_data_2D_EBEE->SetLineStyle(1);
f1::tree_data_2D_EBEE->Draw("leadPt>>h711(100,1.,13000.)","weight");
f2::tree_data_2D_EBEE->SetLineStyle(10);
f2::tree_data_2D_EBEE->SetLineColor(kBlue);
f2::tree_data_2D_EBEE->Draw("leadPt>>h712(100,1.,13000.)","weight","same");
c7.cd(2);
gPad->SetLogy();
gPad->SetLogx();
f1::tree_data_2D_EBEE->SetLineColor(kRed);
f1::tree_data_2D_EBEE->SetLineStyle(1);
f1::tree_data_2D_EBEE->Draw("subleadPt>>h721(100,1.,13000.)","weight");
f2::tree_data_2D_EBEE->SetLineStyle(10);
f2::tree_data_2D_EBEE->SetLineColor(kBlue);
f2::tree_data_2D_EBEE->Draw("subleadPt>>h722(100,1.,13000.)","weight","same");
c7.Update();
TCanvas *c8=new TCanvas("c8","c8")       ;      
c8.Divide(2,1);
c8.cd(1);
gPad->SetLogy();
gPad->SetLogx();
f1::tree_data_2D_EBEB->SetLineColor(kRed);
f1::tree_data_2D_EBEB->SetLineStyle(1);
f1::tree_data_2D_EBEB->Draw("mass>>h811(100,100.,7000.)","weight");
f2::tree_data_2D_EBEB->SetLineStyle(10);
f2::tree_data_2D_EBEB->SetLineColor(kBlue);
f2::tree_data_2D_EBEB->Draw("mass>>h812(100,100.,7000.)","weight","same");
c8.cd(2);
gPad->SetLogy();
gPad->SetLogx();
f1::tree_data_2D_EBEE->SetLineColor(kRed);
f1::tree_data_2D_EBEE->SetLineStyle(1);
f1::tree_data_2D_EBEE->Draw("mass>>h821(100,1.,7000.)","weight");
f2::tree_data_2D_EBEE->SetLineStyle(10);
f2::tree_data_2D_EBEE->SetLineColor(kBlue);
f2::tree_data_2D_EBEE->Draw("mass>>h822(100,1.,7000.)","weight","same");



TFile *f3 = TFile::Open("mix_templatesanv1_v19_137_config256short2NoPreselectionotherhalf.root");
TFile *f4 = TFile::Open("mix_templatesanv1_v19_137_config256short2NoPreselectionhalf.root");
//TFile *f3=TFile::Open("checkofTemplatescreation087/mix_246_v19.root");
//TFile *f4 = TFile::Open("mix_v19_087.root");
//int lenarray=3;
int lenarray=19;
//int lenarray=13;

//double harray[14]={0.,0.1,1.,2.,3.,4.,5.,6.,7.,8.,9.,10.,12.,15.};
TH1F * hiso911=new TH1F("hiso911","hiso911",lenarray,harray);
TH1F * hiso912=new TH1F("hiso912","hiso912",lenarray,harray);
TH1F * hiso921=new TH1F("hiso921","hiso921",lenarray,harray);
TH1F * hiso922=new TH1F("hiso922","hiso922",lenarray,harray);
TH1F * hiso1011=new TH1F("hiso1011","hiso1011",lenarray,harray);
TH1F * hiso1012=new TH1F("hiso1012","hiso1012",lenarray,harray);
TH1F * hiso1021=new TH1F("hiso1021","hiso1021",lenarray,harray);
TH1F * hiso1022=new TH1F("hiso1022","hiso1022",lenarray,harray);
hiso911->SetLineColor(kRed);
hiso911->SetLineStyle(1);
hiso912->SetLineStyle(10);
hiso912->SetLineColor(kBlue);
hiso921->SetLineColor(kRed);
hiso921->SetLineStyle(1);
hiso922->SetLineStyle(10);
hiso922->SetLineColor(kBlue);
hiso1011->SetLineColor(kRed);
hiso1011->SetLineStyle(1);
hiso1012->SetLineStyle(10);
hiso1012->SetLineColor(kBlue);
hiso1021->SetLineColor(kRed);
hiso1021->SetLineStyle(1);
hiso1022->SetLineStyle(10);
hiso1022->SetLineColor(kBlue);

TCanvas *c9=new TCanvas("c9","c9")       ;      
c9.Divide(2,1);
c9.cd(1);
gPad->SetLogy();
f3::tree_template_mix_pf_kDSinglePho2D_EBEE->Draw("templateNdim2Dim0>>hiso911","weight");
f4::tree_template_mix_pf_kDSinglePho2D_EBEE->Draw("templateNdim2Dim0>>hiso912","weight","same");
c9.cd(2);
gPad->SetLogy();
f3::tree_template_mix_pf_kDSinglePho2D_EBEE->Draw("templateNdim2Dim1>>hiso921","weight");
f4::tree_template_mix_pf_kDSinglePho2D_EBEE->Draw("templateNdim2Dim1>>hiso922","weight","same");


TCanvas *c10=new TCanvas("c10","c10")       ;      
c10.Divide(2,1);
c10.cd(1);
gPad->SetLogy();
f3::tree_template_mix_pf_kDSinglePho2D_EBEB->Draw("templateNdim2Dim0>>hiso1011","weight");
f4::tree_template_mix_pf_kDSinglePho2D_EBEB->Draw("templateNdim2Dim0>>hiso1012","weight","same");
c10.cd(2);
gPad->SetLogy();
f3::tree_template_mix_pf_kDSinglePho2D_EBEB->Draw("templateNdim2Dim1>>hiso1021","weight");
f4::tree_template_mix_pf_kDSinglePho2D_EBEB->Draw("templateNdim2Dim1>>hiso1022","weight","same");
}
